Information about the delegates from every state, via [The Green Papers](http://www.thegreenpapers.com/P20/D-Del.phtml)

In [45]:
from convention import Convention

In [46]:
c = Convention()

In [47]:
c.delegate_allocation[c.delegate_allocation.State == 'Iowa']

,State,Pledged,Total,Pledged PLEOs,Unpledged PLEOs,District,At Large,notes
18,Iowa,41.0,49,5,8,27,9,

In [344]:
import numpy as np
df[df.State=='Unassigned']

,Rank,State,Pledged,Unpledged,Total,Details of Allocation,Pledged PLEOs,Unpledged PLEOs,District,At Large
49,50,Unassigned,NaN,5,5,5 Unpledged PLEOs (who must be DNC members),0,5,0,0

In [345]:
df['notes'] = ["must be DNC members" if x == 'Unassigned' else '' for x in df.State]

In [350]:
df = df.drop(columns=['Unpledged','Details of Allocation','Rank']).fillna(0)

In [351]:
df

,State,Pledged,Total,Pledged PLEOs,Unpledged PLEOs,District,At Large,notes
0,Alabama,52.0,61,7,9,34,11,
1,Alaska,15.0,19,2,4,9,4,
2,American Samoa,6.0,11,0,5,0,6,
3,Arizona,67.0,79,9,12,44,14,
4,Arkansas,31.0,36,4,5,20,7,
5,California,415.0,494,54,79,271,90,
6,Colorado,67.0,80,9,13,44,14,
7,Connecticut,60.0,74,6,14,40,14,
8,Delaware,21.0,33,2,12,14,5,
9,Democrats Abroad,13.0,17,1,4,0,12,
10,District of Columbia,20.0,46,2,26,13,5,
11,Florida,219.0,248,29,29,143,47,
12,Georgia,105.0,120,14,15,68,23,
13,Guam,7.0,12,0,5,0,7,
14,Hawaii,24.0,33,3,9,15,6,
15,Idaho,20.0,25,3,5,13,4,
16,Illinois,155.0,184,20,29,101,34,
17,Indiana,82.0,89,9,7,55,18,
18,Iowa,41.0,49,5,8,27,9,
19,Kansas,39.0,45,4,6,26,9,
20,Kentucky,54.0,60,6,6,36,12,
21,Louisiana,54.0,61,7,7,35,12,
22,Maine,24.0,32,3,8,16,5,
23,Maryland,96.0,119,10,23,65,21,
24,Massachusetts,91.0,114,12,23,59,20,
25,Michigan,125.0,147,16,22,82,27,
26,Minnesota,75.0,91,10,16,49,16,
27,Mississippi,36.0,41,5,5,23,8,
28,Missouri,68.0,78,9,10,44,15,
29,Montana,19.0,25,2,6,13,4,
30,Nebraska,29.0,33,3,4,20,6,
31,Nevada,36.0,48,5,12,23,8,
32,New Hampshire,24.0,33,3,9,16,5,
33,New Jersey,126.0,147,14,21,84,28,
34,New Mexico,34.0,45,4,11,23,7,
35,New York,274.0,320,29,46,184,61,
36,North Carolina,110.0,122,14,12,72,24,
37,North Dakota,14.0,18,2,4,9,3,
38,Northern Marianas,6.0,11,0,5,0,6,
39,Ohio,136.0,153,18,17,89,29,
40,Oklahoma,37.0,42,5,5,24,8,
41,Oregon,61.0,75,7,14,41,13,
42,Pennsylvania,186.0,210,20,24,125,41,
43,Puerto Rico,51.0,58,7,7,33,11,
44,Rhode Island,26.0,36,3,10,18,5,
45,South Carolina,54.0,63,7,9,35,12,
46,South Dakota,16.0,21,2,5,10,4,
47,Tennessee,64.0,73,8,9,42,14,
48,Texas,228.0,261,30,33,149,49,
49,Unassigned,0.0,5,0,5,0,0,must be DNC members
50,Utah,29.0,35,4,6,19,6,
51,Vermont,16.0,24,2,8,11,3,
52,Virgin Islands,7.0,13,0,6,0,7,
53,Virginia,99.0,124,13,25,65,21,
54,Washington,89.0,108,12,19,58,19,
55,West Virginia,28.0,34,3,6,19,6,
56,Wisconsin,84.0,97,10,13,55,19,
57,Wyoming,14.0,18,2,4,0,12,
58,Convention,3979.0,4750,490,771,2583,906,